
package by.bsuir.banking.proxy.internetbanking;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IInternetBankingService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IInternetBankingService {


    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfSavedPayment
     * @throws IInternetBankingServiceGetAllSavedPaymentsDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAllSavedPaymentsAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAllSavedPayments", action = "http://tempuri.org/IInternetBankingService/GetAllSavedPayments")
    @WebResult(name = "GetAllSavedPaymentsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllSavedPayments", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllSavedPayments")
    @ResponseWrapper(localName = "GetAllSavedPaymentsResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllSavedPaymentsResponse")
    public ArrayOfSavedPayment getAllSavedPayments(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAllSavedPaymentsAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAllSavedPaymentsDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfSavedPayment
     * @throws IInternetBankingServiceGetSavedPaymentsForAccountDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetSavedPaymentsForAccountAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSavedPaymentsForAccount", action = "http://tempuri.org/IInternetBankingService/GetSavedPaymentsForAccount")
    @WebResult(name = "GetSavedPaymentsForAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSavedPaymentsForAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetSavedPaymentsForAccount")
    @ResponseWrapper(localName = "GetSavedPaymentsForAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetSavedPaymentsForAccountResponse")
    public ArrayOfSavedPayment getSavedPaymentsForAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetSavedPaymentsForAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetSavedPaymentsForAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfRegion
     * @throws IInternetBankingServiceGetAllRegionsAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAllRegionsDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAllRegions", action = "http://tempuri.org/IInternetBankingService/GetAllRegions")
    @WebResult(name = "GetAllRegionsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllRegions", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllRegions")
    @ResponseWrapper(localName = "GetAllRegionsResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllRegionsResponse")
    public ArrayOfRegion getAllRegions(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAllRegionsAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAllRegionsDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param regionId
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfCity
     * @throws IInternetBankingServiceGetCitiesForRegionAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCitiesForRegionDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCitiesForRegion", action = "http://tempuri.org/IInternetBankingService/GetCitiesForRegion")
    @WebResult(name = "GetCitiesForRegionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCitiesForRegion", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCitiesForRegion")
    @ResponseWrapper(localName = "GetCitiesForRegionResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCitiesForRegionResponse")
    public ArrayOfCity getCitiesForRegion(
        @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
        Integer regionId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCitiesForRegionAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCitiesForRegionDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param cityId
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfService
     * @throws IInternetBankingServiceGetServicesForCityAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetServicesForCityDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetServicesForCity", action = "http://tempuri.org/IInternetBankingService/GetServicesForCity")
    @WebResult(name = "GetServicesForCityResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetServicesForCity", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetServicesForCity")
    @ResponseWrapper(localName = "GetServicesForCityResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetServicesForCityResponse")
    public ArrayOfService getServicesForCity(
        @WebParam(name = "cityId", targetNamespace = "http://tempuri.org/")
        Integer cityId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetServicesForCityAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetServicesForCityDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param information
     * @param securityToken
     * @param money
     * @param cardNumber
     * @return
     *     returns java.lang.String
     * @throws IInternetBankingServicePayERIPDomainFaultFaultFaultMessage
     * @throws IInternetBankingServicePayERIPAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "PayERIP", action = "http://tempuri.org/IInternetBankingService/PayERIP")
    @WebResult(name = "PayERIPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PayERIP", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.PayERIP")
    @ResponseWrapper(localName = "PayERIPResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.PayERIPResponse")
    public String payERIP(
        @WebParam(name = "cardNumber", targetNamespace = "http://tempuri.org/")
        String cardNumber,
        @WebParam(name = "money", targetNamespace = "http://tempuri.org/")
        Money money,
        @WebParam(name = "information", targetNamespace = "http://tempuri.org/")
        String information,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServicePayERIPAuthorizationFaultFaultFaultMessage, IInternetBankingServicePayERIPDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param autoPayment
     * @return
     *     returns java.lang.Integer
     * @throws IInternetBankingServiceCreateAutoPaymentAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceCreateAutoPaymentDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateAutoPayment", action = "http://tempuri.org/IInternetBankingService/CreateAutoPayment")
    @WebResult(name = "CreateAutoPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateAutoPayment", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CreateAutoPayment")
    @ResponseWrapper(localName = "CreateAutoPaymentResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CreateAutoPaymentResponse")
    public Integer createAutoPayment(
        @WebParam(name = "autoPayment", targetNamespace = "http://tempuri.org/")
        AutoPayment autoPayment,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceCreateAutoPaymentAuthorizationFaultFaultFaultMessage, IInternetBankingServiceCreateAutoPaymentDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param autoPayment
     * @throws IInternetBankingServiceUpdateAutoPaymentDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceUpdateAutoPaymentAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateAutoPayment", action = "http://tempuri.org/IInternetBankingService/UpdateAutoPayment")
    @RequestWrapper(localName = "UpdateAutoPayment", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdateAutoPayment")
    @ResponseWrapper(localName = "UpdateAutoPaymentResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdateAutoPaymentResponse")
    public void updateAutoPayment(
        @WebParam(name = "autoPayment", targetNamespace = "http://tempuri.org/")
        AutoPayment autoPayment,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceUpdateAutoPaymentAuthorizationFaultFaultFaultMessage, IInternetBankingServiceUpdateAutoPaymentDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param autoPaymentId
     * @param securityToken
     * @throws IInternetBankingServiceDeleteAutoPaymentDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceDeleteAutoPaymentAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeleteAutoPayment", action = "http://tempuri.org/IInternetBankingService/DeleteAutoPayment")
    @RequestWrapper(localName = "DeleteAutoPayment", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.DeleteAutoPayment")
    @ResponseWrapper(localName = "DeleteAutoPaymentResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.DeleteAutoPaymentResponse")
    public void deleteAutoPayment(
        @WebParam(name = "autoPaymentId", targetNamespace = "http://tempuri.org/")
        Integer autoPaymentId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceDeleteAutoPaymentAuthorizationFaultFaultFaultMessage, IInternetBankingServiceDeleteAutoPaymentDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param autoPaymentId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.AutoPayment
     * @throws IInternetBankingServiceGetAutoPaymentDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAutoPaymentAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAutoPayment", action = "http://tempuri.org/IInternetBankingService/GetAutoPayment")
    @WebResult(name = "GetAutoPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAutoPayment", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAutoPayment")
    @ResponseWrapper(localName = "GetAutoPaymentResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAutoPaymentResponse")
    public AutoPayment getAutoPayment(
        @WebParam(name = "autoPaymentId", targetNamespace = "http://tempuri.org/")
        Integer autoPaymentId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAutoPaymentAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAutoPaymentDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfAutoPayment
     * @throws IInternetBankingServiceGetAutoPaymentsForClientAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAutoPaymentsForClientDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAutoPaymentsForClient", action = "http://tempuri.org/IInternetBankingService/GetAutoPaymentsForClient")
    @WebResult(name = "GetAutoPaymentsForClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAutoPaymentsForClient", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAutoPaymentsForClient")
    @ResponseWrapper(localName = "GetAutoPaymentsForClientResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAutoPaymentsForClientResponse")
    public ArrayOfAutoPayment getAutoPaymentsForClient(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAutoPaymentsForClientAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAutoPaymentsForClientDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfAutoPayment
     * @throws IInternetBankingServiceGetAutoPaymentsForAccountDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAutoPaymentsForAccountAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAutoPaymentsForAccount", action = "http://tempuri.org/IInternetBankingService/GetAutoPaymentsForAccount")
    @WebResult(name = "GetAutoPaymentsForAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAutoPaymentsForAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAutoPaymentsForAccount")
    @ResponseWrapper(localName = "GetAutoPaymentsForAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAutoPaymentsForAccountResponse")
    public ArrayOfAutoPayment getAutoPaymentsForAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAutoPaymentsForAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAutoPaymentsForAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param number
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Account
     * @throws IInternetBankingServiceGetAccountByNumberDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAccountByNumberAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountByNumber", action = "http://tempuri.org/IInternetBankingService/GetAccountByNumber")
    @WebResult(name = "GetAccountByNumberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountByNumber", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountByNumber")
    @ResponseWrapper(localName = "GetAccountByNumberResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountByNumberResponse")
    public Account getAccountByNumber(
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAccountByNumberAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAccountByNumberDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Account
     * @throws IInternetBankingServiceGetAccountByIdAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAccountByIdDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountById", action = "http://tempuri.org/IInternetBankingService/GetAccountById")
    @WebResult(name = "GetAccountByIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountById", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountById")
    @ResponseWrapper(localName = "GetAccountByIdResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountByIdResponse")
    public Account getAccountById(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAccountByIdAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAccountByIdDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param account
     * @return
     *     returns java.lang.Integer
     * @throws IInternetBankingServiceOpenAccountAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceOpenAccountDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "OpenAccount", action = "http://tempuri.org/IInternetBankingService/OpenAccount")
    @WebResult(name = "OpenAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OpenAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.OpenAccount")
    @ResponseWrapper(localName = "OpenAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.OpenAccountResponse")
    public Integer openAccount(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        Account account,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceOpenAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceOpenAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @throws IInternetBankingServiceCloseAccountAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceCloseAccountDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CloseAccount", action = "http://tempuri.org/IInternetBankingService/CloseAccount")
    @RequestWrapper(localName = "CloseAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CloseAccount")
    @ResponseWrapper(localName = "CloseAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CloseAccountResponse")
    public void closeAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceCloseAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceCloseAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @param money
     * @throws IInternetBankingServiceReplenishAccountAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceReplenishAccountDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReplenishAccount", action = "http://tempuri.org/IInternetBankingService/ReplenishAccount")
    @RequestWrapper(localName = "ReplenishAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.ReplenishAccount")
    @ResponseWrapper(localName = "ReplenishAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.ReplenishAccountResponse")
    public void replenishAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "money", targetNamespace = "http://tempuri.org/")
        Money money,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceReplenishAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceReplenishAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Card
     * @throws IInternetBankingServiceGetCardForOperatorDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardForOperatorAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCardForOperator", action = "http://tempuri.org/IInternetBankingService/GetCardForOperator")
    @WebResult(name = "GetCardForOperatorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardForOperator", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForOperator")
    @ResponseWrapper(localName = "GetCardForOperatorResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForOperatorResponse")
    public Card getCardForOperator(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardForOperatorAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardForOperatorDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param card
     * @return
     *     returns java.lang.Integer
     * @throws IInternetBankingServiceCreateCardAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceCreateCardDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateCard", action = "http://tempuri.org/IInternetBankingService/CreateCard")
    @WebResult(name = "CreateCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CreateCard")
    @ResponseWrapper(localName = "CreateCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CreateCardResponse")
    public Integer createCard(
        @WebParam(name = "card", targetNamespace = "http://tempuri.org/")
        Card card,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceCreateCardAuthorizationFaultFaultFaultMessage, IInternetBankingServiceCreateCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @throws IInternetBankingServiceDeleteCardAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceDeleteCardDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeleteCard", action = "http://tempuri.org/IInternetBankingService/DeleteCard")
    @RequestWrapper(localName = "DeleteCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.DeleteCard")
    @ResponseWrapper(localName = "DeleteCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.DeleteCardResponse")
    public void deleteCard(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceDeleteCardAuthorizationFaultFaultFaultMessage, IInternetBankingServiceDeleteCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfCardType
     * @throws IInternetBankingServiceGetAllCardTypesDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAllCardTypesAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAllCardTypes", action = "http://tempuri.org/IInternetBankingService/GetAllCardTypes")
    @WebResult(name = "GetAllCardTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllCardTypes", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllCardTypes")
    @ResponseWrapper(localName = "GetAllCardTypesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllCardTypesResponse")
    public ArrayOfCardType getAllCardTypes(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAllCardTypesAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAllCardTypesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param clientId
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfAccount
     * @throws IInternetBankingServiceGetAccountsForClientDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAccountsForClientAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountsForClient", action = "http://tempuri.org/IInternetBankingService/GetAccountsForClient")
    @WebResult(name = "GetAccountsForClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountsForClient", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountsForClient")
    @ResponseWrapper(localName = "GetAccountsForClientResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountsForClientResponse")
    public ArrayOfAccount getAccountsForClient(
        @WebParam(name = "clientId", targetNamespace = "http://tempuri.org/")
        Integer clientId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAccountsForClientAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAccountsForClientDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param clientId
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfCard
     * @throws IInternetBankingServiceGetCardsForClientDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardsForClientAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCardsForClient", action = "http://tempuri.org/IInternetBankingService/GetCardsForClient")
    @WebResult(name = "GetCardsForClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardsForClient", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardsForClient")
    @ResponseWrapper(localName = "GetCardsForClientResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardsForClientResponse")
    public ArrayOfCard getCardsForClient(
        @WebParam(name = "clientId", targetNamespace = "http://tempuri.org/")
        Integer clientId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardsForClientAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardsForClientDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Card
     * @throws IInternetBankingServiceGetCardForAccountDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardForAccountAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCardForAccount", action = "http://tempuri.org/IInternetBankingService/GetCardForAccount")
    @WebResult(name = "GetCardForAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardForAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForAccount")
    @ResponseWrapper(localName = "GetCardForAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForAccountResponse")
    public Card getCardForAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardForAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardForAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Client
     * @throws IInternetBankingServiceGetClientAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetClientDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetClient", action = "http://tempuri.org/IInternetBankingService/GetClient")
    @WebResult(name = "GetClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClient", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetClient")
    @ResponseWrapper(localName = "GetClientResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetClientResponse")
    public Client getClient(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetClientAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetClientDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Card
     * @throws IInternetBankingServiceGetCardForClientAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardForClientDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCardForClient", action = "http://tempuri.org/IInternetBankingService/GetCardForClient")
    @WebResult(name = "GetCardForClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardForClient", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForClient")
    @ResponseWrapper(localName = "GetCardForClientResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForClientResponse")
    public Card getCardForClient(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardForClientAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardForClientDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfCard
     * @throws IInternetBankingServiceGetCardsDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardsAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCards", action = "http://tempuri.org/IInternetBankingService/GetCards")
    @WebResult(name = "GetCardsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCards", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCards")
    @ResponseWrapper(localName = "GetCardsResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardsResponse")
    public ArrayOfCard getCards(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardsAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardsDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Money
     * @throws IInternetBankingServiceGetBallanceAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetBallanceDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetBallance", action = "http://tempuri.org/IInternetBankingService/GetBallance")
    @WebResult(name = "GetBallanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBallance", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetBallance")
    @ResponseWrapper(localName = "GetBallanceResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetBallanceResponse")
    public Money getBallance(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetBallanceAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetBallanceDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param amount
     * @param cardId
     * @param securityToken
     * @param secretWord
     * @throws IInternetBankingServiceSetAmountLimitDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceSetAmountLimitAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetAmountLimit", action = "http://tempuri.org/IInternetBankingService/SetAmountLimit")
    @RequestWrapper(localName = "SetAmountLimit", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetAmountLimit")
    @ResponseWrapper(localName = "SetAmountLimitResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetAmountLimitResponse")
    public void setAmountLimit(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        Money amount,
        @WebParam(name = "secretWord", targetNamespace = "http://tempuri.org/")
        String secretWord,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceSetAmountLimitAuthorizationFaultFaultFaultMessage, IInternetBankingServiceSetAmountLimitDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param count
     * @param securityToken
     * @param secretWord
     * @throws IInternetBankingServiceSetOperationLimitDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceSetOperationLimitAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetOperationLimit", action = "http://tempuri.org/IInternetBankingService/SetOperationLimit")
    @RequestWrapper(localName = "SetOperationLimit", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetOperationLimit")
    @ResponseWrapper(localName = "SetOperationLimitResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetOperationLimitResponse")
    public void setOperationLimit(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        Integer count,
        @WebParam(name = "secretWord", targetNamespace = "http://tempuri.org/")
        String secretWord,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceSetOperationLimitAuthorizationFaultFaultFaultMessage, IInternetBankingServiceSetOperationLimitDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfLegalPerson
     * @throws IInternetBankingServiceGetAllLegalPersonsDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAllLegalPersonsAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAllLegalPersons", action = "http://tempuri.org/IInternetBankingService/GetAllLegalPersons")
    @WebResult(name = "GetAllLegalPersonsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllLegalPersons", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllLegalPersons")
    @ResponseWrapper(localName = "GetAllLegalPersonsResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllLegalPersonsResponse")
    public ArrayOfLegalPerson getAllLegalPersons(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAllLegalPersonsAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAllLegalPersonsDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param newLogin
     * @throws IInternetBankingServiceSetNewLoginAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceSetNewLoginDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetNewLogin", action = "http://tempuri.org/IInternetBankingService/SetNewLogin")
    @RequestWrapper(localName = "SetNewLogin", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetNewLogin")
    @ResponseWrapper(localName = "SetNewLoginResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetNewLoginResponse")
    public void setNewLogin(
        @WebParam(name = "newLogin", targetNamespace = "http://tempuri.org/")
        String newLogin,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceSetNewLoginAuthorizationFaultFaultFaultMessage, IInternetBankingServiceSetNewLoginDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param newPassword
     * @throws IInternetBankingServiceSetNewPasswordAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceSetNewPasswordDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetNewPassword", action = "http://tempuri.org/IInternetBankingService/SetNewPassword")
    @RequestWrapper(localName = "SetNewPassword", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetNewPassword")
    @ResponseWrapper(localName = "SetNewPasswordResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetNewPasswordResponse")
    public void setNewPassword(
        @WebParam(name = "newPassword", targetNamespace = "http://tempuri.org/")
        String newPassword,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceSetNewPasswordAuthorizationFaultFaultFaultMessage, IInternetBankingServiceSetNewPasswordDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfCurrencyType
     * @throws IInternetBankingServiceGetCurrencyTypesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCurrencyTypes", action = "http://tempuri.org/IInternetBankingService/GetCurrencyTypes")
    @WebResult(name = "GetCurrencyTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCurrencyTypes", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCurrencyTypes")
    @ResponseWrapper(localName = "GetCurrencyTypesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCurrencyTypesResponse")
    public ArrayOfCurrencyType getCurrencyTypes()
        throws IInternetBankingServiceGetCurrencyTypesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfSellCurrencyRate
     * @throws IInternetBankingServiceGetSellCurrencyRatesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSellCurrencyRates", action = "http://tempuri.org/IInternetBankingService/GetSellCurrencyRates")
    @WebResult(name = "GetSellCurrencyRatesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSellCurrencyRates", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetSellCurrencyRates")
    @ResponseWrapper(localName = "GetSellCurrencyRatesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetSellCurrencyRatesResponse")
    public ArrayOfSellCurrencyRate getSellCurrencyRates()
        throws IInternetBankingServiceGetSellCurrencyRatesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfPurchaseCurrencyRate
     * @throws IInternetBankingServiceGetPurchaseCurrencyRatesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPurchaseCurrencyRates", action = "http://tempuri.org/IInternetBankingService/GetPurchaseCurrencyRates")
    @WebResult(name = "GetPurchaseCurrencyRatesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPurchaseCurrencyRates", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPurchaseCurrencyRates")
    @ResponseWrapper(localName = "GetPurchaseCurrencyRatesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPurchaseCurrencyRatesResponse")
    public ArrayOfPurchaseCurrencyRate getPurchaseCurrencyRates()
        throws IInternetBankingServiceGetPurchaseCurrencyRatesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param sellCurrencyRates
     * @throws IInternetBankingServiceUpdateSellCurrencyRatesDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceUpdateSellCurrencyRatesAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateSellCurrencyRates", action = "http://tempuri.org/IInternetBankingService/UpdateSellCurrencyRates")
    @RequestWrapper(localName = "UpdateSellCurrencyRates", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdateSellCurrencyRates")
    @ResponseWrapper(localName = "UpdateSellCurrencyRatesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdateSellCurrencyRatesResponse")
    public void updateSellCurrencyRates(
        @WebParam(name = "sellCurrencyRates", targetNamespace = "http://tempuri.org/")
        ArrayOfSellCurrencyRate sellCurrencyRates,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceUpdateSellCurrencyRatesAuthorizationFaultFaultFaultMessage, IInternetBankingServiceUpdateSellCurrencyRatesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param purchaseCurrencyRates
     * @throws IInternetBankingServiceUpdatePurchaseCurrencyRatesAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceUpdatePurchaseCurrencyRatesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdatePurchaseCurrencyRates", action = "http://tempuri.org/IInternetBankingService/UpdatePurchaseCurrencyRates")
    @RequestWrapper(localName = "UpdatePurchaseCurrencyRates", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdatePurchaseCurrencyRates")
    @ResponseWrapper(localName = "UpdatePurchaseCurrencyRatesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdatePurchaseCurrencyRatesResponse")
    public void updatePurchaseCurrencyRates(
        @WebParam(name = "purchaseCurrencyRates", targetNamespace = "http://tempuri.org/")
        ArrayOfPurchaseCurrencyRate purchaseCurrencyRates,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceUpdatePurchaseCurrencyRatesAuthorizationFaultFaultFaultMessage, IInternetBankingServiceUpdatePurchaseCurrencyRatesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param secretWord
     * @param number
     * @throws IInternetBankingServiceLockCardDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "LockCard", action = "http://tempuri.org/IInternetBankingService/LockCard")
    @RequestWrapper(localName = "LockCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.LockCard")
    @ResponseWrapper(localName = "LockCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.LockCardResponse")
    public void lockCard(
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "secretWord", targetNamespace = "http://tempuri.org/")
        String secretWord)
        throws IInternetBankingServiceLockCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param secretWord
     * @param number
     * @throws IInternetBankingServiceUnlockCardDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UnlockCard", action = "http://tempuri.org/IInternetBankingService/UnlockCard")
    @RequestWrapper(localName = "UnlockCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UnlockCard")
    @ResponseWrapper(localName = "UnlockCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UnlockCardResponse")
    public void unlockCard(
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "secretWord", targetNamespace = "http://tempuri.org/")
        String secretWord)
        throws IInternetBankingServiceUnlockCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @throws IInternetBankingServiceLockCardByIdDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceLockCardByIdAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "LockCardById", action = "http://tempuri.org/IInternetBankingService/LockCardById")
    @RequestWrapper(localName = "LockCardById", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.LockCardById")
    @ResponseWrapper(localName = "LockCardByIdResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.LockCardByIdResponse")
    public void lockCardById(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceLockCardByIdAuthorizationFaultFaultFaultMessage, IInternetBankingServiceLockCardByIdDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @throws IInternetBankingServiceUnlockCardByIdDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceUnlockCardByIdAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UnlockCardById", action = "http://tempuri.org/IInternetBankingService/UnlockCardById")
    @RequestWrapper(localName = "UnlockCardById", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UnlockCardById")
    @ResponseWrapper(localName = "UnlockCardByIdResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UnlockCardByIdResponse")
    public void unlockCardById(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceUnlockCardByIdAuthorizationFaultFaultFaultMessage, IInternetBankingServiceUnlockCardByIdDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param amount
     * @param information
     * @param securityToken
     * @param receiverLegalAccountNumber
     * @param cardNumber
     * @return
     *     returns java.lang.String
     * @throws IInternetBankingServicePayAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServicePayDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Pay", action = "http://tempuri.org/IInternetBankingService/Pay")
    @WebResult(name = "PayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Pay", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.Pay")
    @ResponseWrapper(localName = "PayResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.PayResponse")
    public String pay(
        @WebParam(name = "cardNumber", targetNamespace = "http://tempuri.org/")
        String cardNumber,
        @WebParam(name = "receiverLegalAccountNumber", targetNamespace = "http://tempuri.org/")
        String receiverLegalAccountNumber,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        Money amount,
        @WebParam(name = "information", targetNamespace = "http://tempuri.org/")
        String information,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServicePayAuthorizationFaultFaultFaultMessage, IInternetBankingServicePayDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfLegalPersonCategory
     * @throws IInternetBankingServiceGetAllLegalPersonCategoriesAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAllLegalPersonCategoriesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAllLegalPersonCategories", action = "http://tempuri.org/IInternetBankingService/GetAllLegalPersonCategories")
    @WebResult(name = "GetAllLegalPersonCategoriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllLegalPersonCategories", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllLegalPersonCategories")
    @ResponseWrapper(localName = "GetAllLegalPersonCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllLegalPersonCategoriesResponse")
    public ArrayOfLegalPersonCategory getAllLegalPersonCategories(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAllLegalPersonCategoriesAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAllLegalPersonCategoriesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param legalPersonId
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.LegalPerson
     * @throws IInternetBankingServiceGetLegalPersonByIdAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetLegalPersonByIdDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetLegalPersonById", action = "http://tempuri.org/IInternetBankingService/GetLegalPersonById")
    @WebResult(name = "GetLegalPersonByIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLegalPersonById", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetLegalPersonById")
    @ResponseWrapper(localName = "GetLegalPersonByIdResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetLegalPersonByIdResponse")
    public LegalPerson getLegalPersonById(
        @WebParam(name = "legalPersonId", targetNamespace = "http://tempuri.org/")
        Integer legalPersonId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetLegalPersonByIdAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetLegalPersonByIdDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param legalPersonCategoryId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfLegalPerson
     * @throws IInternetBankingServiceGetLegalPersonsForCategoryDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetLegalPersonsForCategoryAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetLegalPersonsForCategory", action = "http://tempuri.org/IInternetBankingService/GetLegalPersonsForCategory")
    @WebResult(name = "GetLegalPersonsForCategoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLegalPersonsForCategory", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetLegalPersonsForCategory")
    @ResponseWrapper(localName = "GetLegalPersonsForCategoryResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetLegalPersonsForCategoryResponse")
    public ArrayOfLegalPerson getLegalPersonsForCategory(
        @WebParam(name = "legalPersonCategoryId", targetNamespace = "http://tempuri.org/")
        Integer legalPersonCategoryId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetLegalPersonsForCategoryAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetLegalPersonsForCategoryDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @param dateTimeTo
     * @param dateTimeFrom
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfPayment
     * @throws IInternetBankingServiceGetPeriodPaymentsForAccountDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetPeriodPaymentsForAccountAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPeriodPaymentsForAccount", action = "http://tempuri.org/IInternetBankingService/GetPeriodPaymentsForAccount")
    @WebResult(name = "GetPeriodPaymentsForAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPeriodPaymentsForAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodPaymentsForAccount")
    @ResponseWrapper(localName = "GetPeriodPaymentsForAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodPaymentsForAccountResponse")
    public ArrayOfPayment getPeriodPaymentsForAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "dateTimeFrom", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeFrom,
        @WebParam(name = "dateTimeTo", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeTo,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetPeriodPaymentsForAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetPeriodPaymentsForAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @param dateTimeTo
     * @param dateTimeFrom
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfPayment
     * @throws IInternetBankingServiceGetPeriodPaymentsForCardAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetPeriodPaymentsForCardDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPeriodPaymentsForCard", action = "http://tempuri.org/IInternetBankingService/GetPeriodPaymentsForCard")
    @WebResult(name = "GetPeriodPaymentsForCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPeriodPaymentsForCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodPaymentsForCard")
    @ResponseWrapper(localName = "GetPeriodPaymentsForCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodPaymentsForCardResponse")
    public ArrayOfPayment getPeriodPaymentsForCard(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "dateTimeFrom", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeFrom,
        @WebParam(name = "dateTimeTo", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeTo,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetPeriodPaymentsForCardAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetPeriodPaymentsForCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param amount
     * @param receiverCardNumber
     * @param securityToken
     * @param cardNumber
     * @return
     *     returns java.lang.String
     * @throws IInternetBankingServiceExecuteTransferDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceExecuteTransferAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ExecuteTransfer", action = "http://tempuri.org/IInternetBankingService/ExecuteTransfer")
    @WebResult(name = "ExecuteTransferResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecuteTransfer", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.ExecuteTransfer")
    @ResponseWrapper(localName = "ExecuteTransferResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.ExecuteTransferResponse")
    public String executeTransfer(
        @WebParam(name = "cardNumber", targetNamespace = "http://tempuri.org/")
        String cardNumber,
        @WebParam(name = "receiverCardNumber", targetNamespace = "http://tempuri.org/")
        String receiverCardNumber,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        Money amount,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceExecuteTransferAuthorizationFaultFaultFaultMessage, IInternetBankingServiceExecuteTransferDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @param dateTimeTo
     * @param dateTimeFrom
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfTransfer
     * @throws IInternetBankingServiceGetPeriodTransfersForAccountDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetPeriodTransfersForAccountAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPeriodTransfersForAccount", action = "http://tempuri.org/IInternetBankingService/GetPeriodTransfersForAccount")
    @WebResult(name = "GetPeriodTransfersForAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPeriodTransfersForAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodTransfersForAccount")
    @ResponseWrapper(localName = "GetPeriodTransfersForAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodTransfersForAccountResponse")
    public ArrayOfTransfer getPeriodTransfersForAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "dateTimeFrom", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeFrom,
        @WebParam(name = "dateTimeTo", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeTo,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetPeriodTransfersForAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetPeriodTransfersForAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @param dateTimeTo
     * @param dateTimeFrom
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfTransfer
     * @throws IInternetBankingServiceGetPeriodTransfersForCardDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetPeriodTransfersForCardAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPeriodTransfersForCard", action = "http://tempuri.org/IInternetBankingService/GetPeriodTransfersForCard")
    @WebResult(name = "GetPeriodTransfersForCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPeriodTransfersForCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodTransfersForCard")
    @ResponseWrapper(localName = "GetPeriodTransfersForCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodTransfersForCardResponse")
    public ArrayOfTransfer getPeriodTransfersForCard(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "dateTimeFrom", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeFrom,
        @WebParam(name = "dateTimeTo", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeTo,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetPeriodTransfersForCardAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetPeriodTransfersForCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param savedPayment
     * @return
     *     returns java.lang.Integer
     * @throws IInternetBankingServiceCreateSavedPaymentDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceCreateSavedPaymentAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateSavedPayment", action = "http://tempuri.org/IInternetBankingService/CreateSavedPayment")
    @WebResult(name = "CreateSavedPaymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateSavedPayment", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CreateSavedPayment")
    @ResponseWrapper(localName = "CreateSavedPaymentResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CreateSavedPaymentResponse")
    public Integer createSavedPayment(
        @WebParam(name = "savedPayment", targetNamespace = "http://tempuri.org/")
        SavedPayment savedPayment,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceCreateSavedPaymentAuthorizationFaultFaultFaultMessage, IInternetBankingServiceCreateSavedPaymentDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param savedPayment
     * @throws IInternetBankingServiceUpdateSavedPaymentDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceUpdateSavedPaymentAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateSavedPayment", action = "http://tempuri.org/IInternetBankingService/UpdateSavedPayment")
    @RequestWrapper(localName = "UpdateSavedPayment", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdateSavedPayment")
    @ResponseWrapper(localName = "UpdateSavedPaymentResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdateSavedPaymentResponse")
    public void updateSavedPayment(
        @WebParam(name = "savedPayment", targetNamespace = "http://tempuri.org/")
        SavedPayment savedPayment,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceUpdateSavedPaymentAuthorizationFaultFaultFaultMessage, IInternetBankingServiceUpdateSavedPaymentDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param deletedSavedPaymentId
     * @throws IInternetBankingServiceDeleteSavedPaymentAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceDeleteSavedPaymentDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeleteSavedPayment", action = "http://tempuri.org/IInternetBankingService/DeleteSavedPayment")
    @RequestWrapper(localName = "DeleteSavedPayment", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.DeleteSavedPayment")
    @ResponseWrapper(localName = "DeleteSavedPaymentResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.DeleteSavedPaymentResponse")
    public void deleteSavedPayment(
        @WebParam(name = "deletedSavedPaymentId", targetNamespace = "http://tempuri.org/")
        Integer deletedSavedPaymentId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceDeleteSavedPaymentAuthorizationFaultFaultFaultMessage, IInternetBankingServiceDeleteSavedPaymentDomainFaultFaultFaultMessage
    ;

}
