
package by.bsuir.banking.proxy.lockcard;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LockCardService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8737/LockCardService/?wsdl")
public class LockCardService
    extends Service
{

    private final static URL LOCKCARDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(by.bsuir.banking.proxy.lockcard.LockCardService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = by.bsuir.banking.proxy.lockcard.LockCardService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8737/LockCardService/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8737/LockCardService/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOCKCARDSERVICE_WSDL_LOCATION = url;
    }

    public LockCardService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LockCardService() {
        super(LOCKCARDSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "LockCardService"));
    }

    /**
     * 
     * @return
     *     returns ILockCardService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILockCardService")
    public ILockCardService getBasicHttpBindingILockCardService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ILockCardService"), ILockCardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILockCardService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILockCardService")
    public ILockCardService getBasicHttpBindingILockCardService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ILockCardService"), ILockCardService.class, features);
    }

}
