
package by.bsuir.banking.proxy.operator;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OperatorService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8735/OperatorService/?wsdl")
public class OperatorService
    extends Service
{

    private final static URL OPERATORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(by.bsuir.banking.proxy.operator.OperatorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = by.bsuir.banking.proxy.operator.OperatorService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8735/OperatorService/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8735/OperatorService/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OPERATORSERVICE_WSDL_LOCATION = url;
    }

    public OperatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperatorService() {
        super(OPERATORSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "OperatorService"));
    }

    /**
     * 
     * @return
     *     returns IOperatorService
     */
    @WebEndpoint(name = "BasicHttpBinding_IOperatorService")
    public IOperatorService getBasicHttpBindingIOperatorService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IOperatorService"), IOperatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOperatorService
     */
    @WebEndpoint(name = "BasicHttpBinding_IOperatorService")
    public IOperatorService getBasicHttpBindingIOperatorService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IOperatorService"), IOperatorService.class, features);
    }

}
