
package by.bsuir.banking.proxy.card;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CardService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8736/CardService/?wsdl")
public class CardService
    extends Service
{

    private final static URL CARDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(by.bsuir.banking.proxy.card.CardService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = by.bsuir.banking.proxy.card.CardService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8736/CardService/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8736/CardService/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CARDSERVICE_WSDL_LOCATION = url;
    }

    public CardService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardService() {
        super(CARDSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "CardService"));
    }

    /**
     * 
     * @return
     *     returns ICardService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICardService")
    public ICardService getBasicHttpBindingICardService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICardService"), ICardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICardService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICardService")
    public ICardService getBasicHttpBindingICardService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICardService"), ICardService.class, features);
    }

}
