
package by.bsuir.banking.proxy.lockcard;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ILockCardService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILockCardService {


    /**
     * 
     * @param securityToken
     * @param secretWord
     * @param number
     */
    @WebMethod(operationName = "LockCard", action = "http://tempuri.org/ILockCardService/LockCard")
    @RequestWrapper(localName = "LockCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.lockcard.LockCard")
    @ResponseWrapper(localName = "LockCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.lockcard.LockCardResponse")
    public void lockCard(
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "secretWord", targetNamespace = "http://tempuri.org/")
        String secretWord,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken);

    /**
     * 
     * @param securityToken
     * @param secretWord
     * @param number
     */
    @WebMethod(operationName = "UnlockCard", action = "http://tempuri.org/ILockCardService/UnlockCard")
    @RequestWrapper(localName = "UnlockCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.lockcard.UnlockCard")
    @ResponseWrapper(localName = "UnlockCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.lockcard.UnlockCardResponse")
    public void unlockCard(
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "secretWord", targetNamespace = "http://tempuri.org/")
        String secretWord,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken);

}
