
package by.bsuir.banking.proxy.internetbanking;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IInternetBankingService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IInternetBankingService {


    /**
     * 
     * @param securityToken
     * @param number
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Account
     * @throws IInternetBankingServiceGetAccountByNumberDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAccountByNumberAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountByNumber", action = "http://tempuri.org/IInternetBankingService/GetAccountByNumber")
    @WebResult(name = "GetAccountByNumberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountByNumber", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountByNumber")
    @ResponseWrapper(localName = "GetAccountByNumberResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountByNumberResponse")
    public Account getAccountByNumber(
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAccountByNumberAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAccountByNumberDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Account
     * @throws IInternetBankingServiceGetAccountByIdDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAccountByIdAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountById", action = "http://tempuri.org/IInternetBankingService/GetAccountById")
    @WebResult(name = "GetAccountByIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountById", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountById")
    @ResponseWrapper(localName = "GetAccountByIdResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountByIdResponse")
    public Account getAccountById(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAccountByIdAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAccountByIdDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param account
     * @return
     *     returns java.lang.Integer
     * @throws IInternetBankingServiceOpenAccountDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceOpenAccountAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "OpenAccount", action = "http://tempuri.org/IInternetBankingService/OpenAccount")
    @WebResult(name = "OpenAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OpenAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.OpenAccount")
    @ResponseWrapper(localName = "OpenAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.OpenAccountResponse")
    public Integer openAccount(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        Account account,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceOpenAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceOpenAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @throws IInternetBankingServiceCloseAccountDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceCloseAccountAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CloseAccount", action = "http://tempuri.org/IInternetBankingService/CloseAccount")
    @RequestWrapper(localName = "CloseAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CloseAccount")
    @ResponseWrapper(localName = "CloseAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CloseAccountResponse")
    public void closeAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceCloseAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceCloseAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Card
     * @throws IInternetBankingServiceGetCardForOperatorDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardForOperatorAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCardForOperator", action = "http://tempuri.org/IInternetBankingService/GetCardForOperator")
    @WebResult(name = "GetCardForOperatorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardForOperator", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForOperator")
    @ResponseWrapper(localName = "GetCardForOperatorResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForOperatorResponse")
    public Card getCardForOperator(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardForOperatorAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardForOperatorDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param card
     * @return
     *     returns java.lang.Integer
     * @throws IInternetBankingServiceCreateCardDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceCreateCardAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateCard", action = "http://tempuri.org/IInternetBankingService/CreateCard")
    @WebResult(name = "CreateCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CreateCard")
    @ResponseWrapper(localName = "CreateCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.CreateCardResponse")
    public Integer createCard(
        @WebParam(name = "card", targetNamespace = "http://tempuri.org/")
        Card card,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceCreateCardAuthorizationFaultFaultFaultMessage, IInternetBankingServiceCreateCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @throws IInternetBankingServiceDeleteCardDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceDeleteCardAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeleteCard", action = "http://tempuri.org/IInternetBankingService/DeleteCard")
    @RequestWrapper(localName = "DeleteCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.DeleteCard")
    @ResponseWrapper(localName = "DeleteCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.DeleteCardResponse")
    public void deleteCard(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceDeleteCardAuthorizationFaultFaultFaultMessage, IInternetBankingServiceDeleteCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns java.math.BigDecimal
     * @throws IInternetBankingServiceGetAmountLimitAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAmountLimitDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAmountLimit", action = "http://tempuri.org/IInternetBankingService/GetAmountLimit")
    @WebResult(name = "GetAmountLimitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAmountLimit", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAmountLimit")
    @ResponseWrapper(localName = "GetAmountLimitResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAmountLimitResponse")
    public BigDecimal getAmountLimit(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAmountLimitAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAmountLimitDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns java.lang.Integer
     * @throws IInternetBankingServiceGetOperationLimitAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetOperationLimitDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetOperationLimit", action = "http://tempuri.org/IInternetBankingService/GetOperationLimit")
    @WebResult(name = "GetOperationLimitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOperationLimit", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetOperationLimit")
    @ResponseWrapper(localName = "GetOperationLimitResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetOperationLimitResponse")
    public Integer getOperationLimit(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetOperationLimitAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetOperationLimitDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfCardType
     * @throws IInternetBankingServiceGetAllCardTypesAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAllCardTypesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAllCardTypes", action = "http://tempuri.org/IInternetBankingService/GetAllCardTypes")
    @WebResult(name = "GetAllCardTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllCardTypes", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllCardTypes")
    @ResponseWrapper(localName = "GetAllCardTypesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAllCardTypesResponse")
    public ArrayOfCardType getAllCardTypes(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAllCardTypesAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAllCardTypesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param clientId
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfAccount
     * @throws IInternetBankingServiceGetAccountsForClientDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetAccountsForClientAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountsForClient", action = "http://tempuri.org/IInternetBankingService/GetAccountsForClient")
    @WebResult(name = "GetAccountsForClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountsForClient", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountsForClient")
    @ResponseWrapper(localName = "GetAccountsForClientResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetAccountsForClientResponse")
    public ArrayOfAccount getAccountsForClient(
        @WebParam(name = "clientId", targetNamespace = "http://tempuri.org/")
        Integer clientId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetAccountsForClientAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetAccountsForClientDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param clientId
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfCard
     * @throws IInternetBankingServiceGetCardsForClientDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardsForClientAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCardsForClient", action = "http://tempuri.org/IInternetBankingService/GetCardsForClient")
    @WebResult(name = "GetCardsForClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardsForClient", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardsForClient")
    @ResponseWrapper(localName = "GetCardsForClientResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardsForClientResponse")
    public ArrayOfCard getCardsForClient(
        @WebParam(name = "clientId", targetNamespace = "http://tempuri.org/")
        Integer clientId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardsForClientAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardsForClientDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Card
     * @throws IInternetBankingServiceGetCardForAccountDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardForAccountAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCardForAccount", action = "http://tempuri.org/IInternetBankingService/GetCardForAccount")
    @WebResult(name = "GetCardForAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardForAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForAccount")
    @ResponseWrapper(localName = "GetCardForAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForAccountResponse")
    public Card getCardForAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardForAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardForAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Card
     * @throws IInternetBankingServiceGetCardForClientAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardForClientDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCardForClient", action = "http://tempuri.org/IInternetBankingService/GetCardForClient")
    @WebResult(name = "GetCardForClientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardForClient", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForClient")
    @ResponseWrapper(localName = "GetCardForClientResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardForClientResponse")
    public Card getCardForClient(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardForClientAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardForClientDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfCard
     * @throws IInternetBankingServiceGetCardsDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetCardsAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCards", action = "http://tempuri.org/IInternetBankingService/GetCards")
    @WebResult(name = "GetCardsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCards", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCards")
    @ResponseWrapper(localName = "GetCardsResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCardsResponse")
    public ArrayOfCard getCards(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetCardsAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetCardsDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.Money
     * @throws IInternetBankingServiceGetBallanceDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetBallanceAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetBallance", action = "http://tempuri.org/IInternetBankingService/GetBallance")
    @WebResult(name = "GetBallanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBallance", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetBallance")
    @ResponseWrapper(localName = "GetBallanceResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetBallanceResponse")
    public Money getBallance(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetBallanceAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetBallanceDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param amount
     * @param cardId
     * @param securityToken
     * @throws IInternetBankingServiceSetAmountLimitDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceSetAmountLimitAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetAmountLimit", action = "http://tempuri.org/IInternetBankingService/SetAmountLimit")
    @RequestWrapper(localName = "SetAmountLimit", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetAmountLimit")
    @ResponseWrapper(localName = "SetAmountLimitResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetAmountLimitResponse")
    public void setAmountLimit(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceSetAmountLimitAuthorizationFaultFaultFaultMessage, IInternetBankingServiceSetAmountLimitDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param count
     * @param securityToken
     * @throws IInternetBankingServiceSetOperationLimitDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceSetOperationLimitAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetOperationLimit", action = "http://tempuri.org/IInternetBankingService/SetOperationLimit")
    @RequestWrapper(localName = "SetOperationLimit", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetOperationLimit")
    @ResponseWrapper(localName = "SetOperationLimitResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.SetOperationLimitResponse")
    public void setOperationLimit(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        Integer count,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceSetOperationLimitAuthorizationFaultFaultFaultMessage, IInternetBankingServiceSetOperationLimitDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfCurrencyType
     * @throws IInternetBankingServiceGetCurrencyTypesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCurrencyTypes", action = "http://tempuri.org/IInternetBankingService/GetCurrencyTypes")
    @WebResult(name = "GetCurrencyTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCurrencyTypes", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCurrencyTypes")
    @ResponseWrapper(localName = "GetCurrencyTypesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetCurrencyTypesResponse")
    public ArrayOfCurrencyType getCurrencyTypes()
        throws IInternetBankingServiceGetCurrencyTypesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfSellCurrencyRate
     * @throws IInternetBankingServiceGetSellCurrencyRatesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSellCurrencyRates", action = "http://tempuri.org/IInternetBankingService/GetSellCurrencyRates")
    @WebResult(name = "GetSellCurrencyRatesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSellCurrencyRates", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetSellCurrencyRates")
    @ResponseWrapper(localName = "GetSellCurrencyRatesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetSellCurrencyRatesResponse")
    public ArrayOfSellCurrencyRate getSellCurrencyRates()
        throws IInternetBankingServiceGetSellCurrencyRatesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfPurchaseCurrencyRate
     * @throws IInternetBankingServiceGetPurchaseCurrencyRatesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPurchaseCurrencyRates", action = "http://tempuri.org/IInternetBankingService/GetPurchaseCurrencyRates")
    @WebResult(name = "GetPurchaseCurrencyRatesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPurchaseCurrencyRates", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPurchaseCurrencyRates")
    @ResponseWrapper(localName = "GetPurchaseCurrencyRatesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPurchaseCurrencyRatesResponse")
    public ArrayOfPurchaseCurrencyRate getPurchaseCurrencyRates()
        throws IInternetBankingServiceGetPurchaseCurrencyRatesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param sellCurrencyRates
     * @throws IInternetBankingServiceUpdateSellCurrencyRatesAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceUpdateSellCurrencyRatesDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateSellCurrencyRates", action = "http://tempuri.org/IInternetBankingService/UpdateSellCurrencyRates")
    @RequestWrapper(localName = "UpdateSellCurrencyRates", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdateSellCurrencyRates")
    @ResponseWrapper(localName = "UpdateSellCurrencyRatesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdateSellCurrencyRatesResponse")
    public void updateSellCurrencyRates(
        @WebParam(name = "sellCurrencyRates", targetNamespace = "http://tempuri.org/")
        ArrayOfSellCurrencyRate sellCurrencyRates,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceUpdateSellCurrencyRatesAuthorizationFaultFaultFaultMessage, IInternetBankingServiceUpdateSellCurrencyRatesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @param purchaseCurrencyRates
     * @throws IInternetBankingServiceUpdatePurchaseCurrencyRatesDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceUpdatePurchaseCurrencyRatesAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdatePurchaseCurrencyRates", action = "http://tempuri.org/IInternetBankingService/UpdatePurchaseCurrencyRates")
    @RequestWrapper(localName = "UpdatePurchaseCurrencyRates", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdatePurchaseCurrencyRates")
    @ResponseWrapper(localName = "UpdatePurchaseCurrencyRatesResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UpdatePurchaseCurrencyRatesResponse")
    public void updatePurchaseCurrencyRates(
        @WebParam(name = "purchaseCurrencyRates", targetNamespace = "http://tempuri.org/")
        ArrayOfPurchaseCurrencyRate purchaseCurrencyRates,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceUpdatePurchaseCurrencyRatesAuthorizationFaultFaultFaultMessage, IInternetBankingServiceUpdatePurchaseCurrencyRatesDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param secretWord
     * @param number
     * @throws IInternetBankingServiceLockCardDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "LockCard", action = "http://tempuri.org/IInternetBankingService/LockCard")
    @RequestWrapper(localName = "LockCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.LockCard")
    @ResponseWrapper(localName = "LockCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.LockCardResponse")
    public void lockCard(
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "secretWord", targetNamespace = "http://tempuri.org/")
        String secretWord)
        throws IInternetBankingServiceLockCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param secretWord
     * @param number
     * @throws IInternetBankingServiceUnlockCardDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UnlockCard", action = "http://tempuri.org/IInternetBankingService/UnlockCard")
    @RequestWrapper(localName = "UnlockCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UnlockCard")
    @ResponseWrapper(localName = "UnlockCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UnlockCardResponse")
    public void unlockCard(
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "secretWord", targetNamespace = "http://tempuri.org/")
        String secretWord)
        throws IInternetBankingServiceUnlockCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @throws IInternetBankingServiceLockCardByIdDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceLockCardByIdAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "LockCardById", action = "http://tempuri.org/IInternetBankingService/LockCardById")
    @RequestWrapper(localName = "LockCardById", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.LockCardById")
    @ResponseWrapper(localName = "LockCardByIdResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.LockCardByIdResponse")
    public void lockCardById(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceLockCardByIdAuthorizationFaultFaultFaultMessage, IInternetBankingServiceLockCardByIdDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @throws IInternetBankingServiceUnlockCardByIdDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceUnlockCardByIdAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UnlockCardById", action = "http://tempuri.org/IInternetBankingService/UnlockCardById")
    @RequestWrapper(localName = "UnlockCardById", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UnlockCardById")
    @ResponseWrapper(localName = "UnlockCardByIdResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.UnlockCardByIdResponse")
    public void unlockCardById(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceUnlockCardByIdAuthorizationFaultFaultFaultMessage, IInternetBankingServiceUnlockCardByIdDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param amount
     * @param accountNumber
     * @param securityToken
     * @param receiverAccountNumber
     * @throws IInternetBankingServicePayAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServicePayDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Pay", action = "http://tempuri.org/IInternetBankingService/Pay")
    @RequestWrapper(localName = "Pay", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.Pay")
    @ResponseWrapper(localName = "PayResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.PayResponse")
    public void pay(
        @WebParam(name = "accountNumber", targetNamespace = "http://tempuri.org/")
        String accountNumber,
        @WebParam(name = "receiverAccountNumber", targetNamespace = "http://tempuri.org/")
        String receiverAccountNumber,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        Money amount,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServicePayAuthorizationFaultFaultFaultMessage, IInternetBankingServicePayDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param accountId
     * @param securityToken
     * @param dateTimeTo
     * @param dateTimeFrom
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfPayment
     * @throws IInternetBankingServiceGetPeriodPaymentsForAccountDomainFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetPeriodPaymentsForAccountAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPeriodPaymentsForAccount", action = "http://tempuri.org/IInternetBankingService/GetPeriodPaymentsForAccount")
    @WebResult(name = "GetPeriodPaymentsForAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPeriodPaymentsForAccount", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodPaymentsForAccount")
    @ResponseWrapper(localName = "GetPeriodPaymentsForAccountResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodPaymentsForAccountResponse")
    public ArrayOfPayment getPeriodPaymentsForAccount(
        @WebParam(name = "accountId", targetNamespace = "http://tempuri.org/")
        Integer accountId,
        @WebParam(name = "dateTimeFrom", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeFrom,
        @WebParam(name = "dateTimeTo", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeTo,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetPeriodPaymentsForAccountAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetPeriodPaymentsForAccountDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @param dateTimeTo
     * @param dateTimeFrom
     * @return
     *     returns by.bsuir.banking.proxy.internetbanking.ArrayOfPayment
     * @throws IInternetBankingServiceGetPeriodPaymentsForCardAuthorizationFaultFaultFaultMessage
     * @throws IInternetBankingServiceGetPeriodPaymentsForCardDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPeriodPaymentsForCard", action = "http://tempuri.org/IInternetBankingService/GetPeriodPaymentsForCard")
    @WebResult(name = "GetPeriodPaymentsForCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPeriodPaymentsForCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodPaymentsForCard")
    @ResponseWrapper(localName = "GetPeriodPaymentsForCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.internetbanking.GetPeriodPaymentsForCardResponse")
    public ArrayOfPayment getPeriodPaymentsForCard(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "dateTimeFrom", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeFrom,
        @WebParam(name = "dateTimeTo", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTimeTo,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IInternetBankingServiceGetPeriodPaymentsForCardAuthorizationFaultFaultFaultMessage, IInternetBankingServiceGetPeriodPaymentsForCardDomainFaultFaultFaultMessage
    ;

}
