
package by.bsuir.banking.proxy.authentication;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AuthenticationService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8733/AuthenticationService/?wsdl")
public class AuthenticationService
    extends Service
{

    private final static URL AUTHENTICATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(by.bsuir.banking.proxy.authentication.AuthenticationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = by.bsuir.banking.proxy.authentication.AuthenticationService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8733/AuthenticationService/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8733/AuthenticationService/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTHENTICATIONSERVICE_WSDL_LOCATION = url;
    }

    public AuthenticationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationService() {
        super(AUTHENTICATIONSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "AuthenticationService"));
    }

    /**
     * 
     * @return
     *     returns IAuthenticationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAuthenticationService")
    public IAuthenticationService getBasicHttpBindingIAuthenticationService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAuthenticationService"), IAuthenticationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAuthenticationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAuthenticationService")
    public IAuthenticationService getBasicHttpBindingIAuthenticationService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAuthenticationService"), IAuthenticationService.class, features);
    }

}
