
package by.bsuir.banking.proxy.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IAuthenticationService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAuthenticationService {


    /**
     * 
     * @param login
     * @param password
     * @return
     *     returns by.bsuir.banking.proxy.authentication.AuthenticationCredential
     * @throws IAuthenticationServiceAuthenticateAuthenticationFaultFaultFaultMessage
     * @throws IAuthenticationServiceAuthenticateDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Authenticate", action = "http://tempuri.org/IAuthenticationService/Authenticate")
    @WebResult(name = "AuthenticateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.authentication.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.authentication.AuthenticateResponse")
    public AuthenticationCredential authenticate(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password)
        throws IAuthenticationServiceAuthenticateAuthenticationFaultFaultFaultMessage, IAuthenticationServiceAuthenticateDomainFaultFaultFaultMessage
    ;

}
