
package by.bsuir.banking.dotnetclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "DomainFault", targetNamespace = "http://schemas.datacontract.org/2004/07/InternetBanking.Services.Interfaces.FaultContracts")
public class IAdministrationServiceRemoveOperatorDomainFaultFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DomainFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IAdministrationServiceRemoveOperatorDomainFaultFaultFaultMessage(String message, DomainFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IAdministrationServiceRemoveOperatorDomainFaultFaultFaultMessage(String message, DomainFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: by.bsuir.banking.dotnetclient.DomainFault
     */
    public DomainFault getFaultInfo() {
        return faultInfo;
    }

}
