
package by.bsuir.banking.proxy.client;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IClientService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IClientService {


    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.client.Card
     * @throws IClientServiceGetCardDomainFaultFaultFaultMessage
     * @throws IClientServiceGetCardAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCard", action = "http://tempuri.org/IClientService/GetCard")
    @WebResult(name = "GetCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCard", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.GetCard")
    @ResponseWrapper(localName = "GetCardResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.GetCardResponse")
    public Card getCard(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IClientServiceGetCardAuthorizationFaultFaultFaultMessage, IClientServiceGetCardDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.client.ArrayOfCard
     * @throws IClientServiceGetCardsDomainFaultFaultFaultMessage
     * @throws IClientServiceGetCardsAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCards", action = "http://tempuri.org/IClientService/GetCards")
    @WebResult(name = "GetCardsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCards", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.GetCards")
    @ResponseWrapper(localName = "GetCardsResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.GetCardsResponse")
    public ArrayOfCard getCards(
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IClientServiceGetCardsAuthorizationFaultFaultFaultMessage, IClientServiceGetCardsDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param securityToken
     * @return
     *     returns by.bsuir.banking.proxy.client.Money
     * @throws IClientServiceGetBallanceAuthorizationFaultFaultFaultMessage
     * @throws IClientServiceGetBallanceDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetBallance", action = "http://tempuri.org/IClientService/GetBallance")
    @WebResult(name = "GetBallanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBallance", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.GetBallance")
    @ResponseWrapper(localName = "GetBallanceResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.GetBallanceResponse")
    public Money getBallance(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IClientServiceGetBallanceAuthorizationFaultFaultFaultMessage, IClientServiceGetBallanceDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param amount
     * @param cardId
     * @param securityToken
     * @throws IClientServiceSetAmountLimitDomainFaultFaultFaultMessage
     * @throws IClientServiceSetAmountLimitAuthorizationFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetAmountLimit", action = "http://tempuri.org/IClientService/SetAmountLimit")
    @RequestWrapper(localName = "SetAmountLimit", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.SetAmountLimit")
    @ResponseWrapper(localName = "SetAmountLimitResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.SetAmountLimitResponse")
    public void setAmountLimit(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IClientServiceSetAmountLimitAuthorizationFaultFaultFaultMessage, IClientServiceSetAmountLimitDomainFaultFaultFaultMessage
    ;

    /**
     * 
     * @param cardId
     * @param count
     * @param securityToken
     * @throws IClientServiceSetOperationLimitAuthorizationFaultFaultFaultMessage
     * @throws IClientServiceSetOperationLimitDomainFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetOperationLimit", action = "http://tempuri.org/IClientService/SetOperationLimit")
    @RequestWrapper(localName = "SetOperationLimit", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.SetOperationLimit")
    @ResponseWrapper(localName = "SetOperationLimitResponse", targetNamespace = "http://tempuri.org/", className = "by.bsuir.banking.proxy.client.SetOperationLimitResponse")
    public void setOperationLimit(
        @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
        Integer cardId,
        @WebParam(name = "count", targetNamespace = "http://tempuri.org/")
        Integer count,
        @WebParam(name = "securityToken", targetNamespace = "http://tempuri.org/")
        String securityToken)
        throws IClientServiceSetOperationLimitAuthorizationFaultFaultFaultMessage, IClientServiceSetOperationLimitDomainFaultFaultFaultMessage
    ;

}
